# Dataset Load and Initial Inspection

In [1]:
import pandas as pd
data =pd.read_csv("data_clean.csv")
data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [2]:
data_backup =data # Taking backup of originmal data

In [3]:
data.tail(10)

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
148         149   30.0    193.0   6.9     70     9   26  2010    70       C
149         150    NaN    145.0  13.2     77     9   27  2010    77      PS
150         151   14.0    191.0  14.3     75     9   28  2010    75       S
151         152   18.0    131.0   8.0     76     9   29  2010    76      PS
152         153   20.0    223.0  11.5     68     9   30  2010    68       S
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  158 non-null    int64
 1   Ozone       120 non-null    float64
 2   Solar.R     151 non-null    float64
 3   Wind        158 non-null    float64
 4   Temp C      158 non-null    object
 5   Month       158 non-null    object
 6   Day         158 non-null    int64
 7   Year        158 non-null    int64
 8   Temp        158 non-null    int64
 9   Weather     155 non-null    object
dtypes: float64(3), int64(4), object(3)
memory usage: 12.5+ KB

In [5]:
data.shape

(158, 10)

In [6]:
data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [7]:
data.describe() # Basic Statistics

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

## Datatype Conversions

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  158 non-null    int64
 1   Ozone       120 non-null    float64
 2   Solar.R     151 non-null    float64
 3   Wind        158 non-null    float64
 4   Temp C      158 non-null    object
 5   Month       158 non-null    object
 6   Day         158 non-null    int64
 7   Year        158 non-null    int64
 8   Temp        158 non-null    int64
 9   Weather     155 non-null    object
dtypes: float64(3), int64(4), object(3)
memory usage: 12.5+ KB

In [11]:
# This line shows an error
data.Month = pd.to_numeric(data.Month)

ValueError: Unable to parse string "May" at position 23

In [12]:
#  The element at 23rd index is not integer it is object(String)
data .Month.head(25)

0       5
1       5
2       5
3       5
4       5
5       5
6       5
7       5
8       5
9       5
10      5
11      5
12      5
13      5
14      5
15      5
16      5
17      5
18      5
19      5
20      5
21      5
22      5
23    May
24      5
Name: Month, dtype: object

In [13]:
# So we have to replace May with 5
data.Month = data.Month.replace("May",5)
data.Month.head(25)

0     5
1     5
2     5
3     5
4     5
5     5
6     5
7     5
8     5
9     5
10    5
11    5
12    5
13    5
14    5
15    5
16    5
17    5
18    5
19    5
20    5
21    5
22    5
23    5
24    5
Name: Month, dtype: object

In [18]:
# Now do datatype coversion 
data.Month = pd.to_numeric(data.Month, errors="coerce") # errors="coerse" forces any nother value to convert like May to NA
data["Temp C"] = pd.to_numeric(data["Temp C"], errors="coerce")
data["Weather"] = data["Weather"].astype("category")

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  158 non-null    int64
 1   Ozone       120 non-null    float64
 2   Solar.R     151 non-null    float64
 3   Wind        158 non-null    float64
 4   Temp C      157 non-null    float64
 5   Month       158 non-null    int64
 6   Day         158 non-null    int64
 7   Year        158 non-null    int64
 8   Temp        158 non-null    int64
 9   Weather     155 non-null    category
dtypes: category(1), float64(4), int64(5)
memory usage: 11.5 KB

## Duplicates

In [20]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
153    False
154    False
155    False
156    False
157    False
Length: 158, dtype: bool

In [21]:
# Count of duplicate rows
data[data.duplicated()].shape

(0, 10)

In [22]:
# Print the duplicated rows
data[data.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, Ozone, Solar.R, Wind, Temp C, Month, Day, Year, Temp, Weather]
Index: []

In [23]:
# If duplicate records found, you drop the, by this
data =data.drop_duplicates()

In [24]:
data.shape

(158, 10)

## Drop unncessary columns

In [25]:
data.head()

   Unnamed: 0  Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4    67.0      5    1  2010    67       S
1           2   36.0    118.0   8.0    72.0      5    2  2010    72       C
2           3   12.0    149.0  12.6    74.0      5    3  2010    74      PS
3           4   18.0    313.0  11.5    62.0      5    4  2010    62       S
4           5    NaN      NaN  14.3    56.0      5    5  2010    56       S

In [26]:
# Taking backup one more time before removing removing anything
data_backup2 = data

In [27]:
data = data.drop("Unnamed: 0",axis=1)
data.head()

   Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
0   41.0    190.0   7.4    67.0      5    1  2010    67       S
1   36.0    118.0   8.0    72.0      5    2  2010    72       C
2   12.0    149.0  12.6    74.0      5    3  2010    74      PS
3   18.0    313.0  11.5    62.0      5    4  2010    62       S
4    NaN      NaN  14.3    56.0      5    5  2010    56       S