# 🔍🚗 Decision Tree Classifier machine learning algorithm to predict the safety of the car (unacceptable, acceptable,good , very good) with Python

## Problem Statement
### A car dealership and manufacturing company wants to develop a predictive model to automatically evaluate the safety level of

### vehicles based on their key attributes.

Currently, safety assessments require expensive crash tests and expert evaluations, which are time-consuming and resource-intensive.

### Business Impact
The inability to quickly and accurately assess vehicle safety leads to:

Increased costs from extensive physical testing

Slower time-to-market for new vehicle models

Inconsistent safety evaluations due to subjective human judgment

Missed opportunities to optimize vehicle designs for safety early in development

HERE we build a Decision Tree Classifier to predict the safety of the car. We build two models, one with criterion gini index

and another one with criterion entropy. Implemention Decision Tree Classification with Python and Scikit-Learn.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('car_evaluation.csv',header=None)

In [5]:
df.head()

       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

### Analyzing Data

In [6]:
df.shape

(1728, 7)

In [7]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_names
col_names

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [8]:
df.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [9]:
df.tail()

     buying maint  doors persons lug_boot safety  class
1723    low   low  5more    more      med    med   good
1724    low   low  5more    more      med   high  vgood
1725    low   low  5more    more      big    low  unacc
1726    low   low  5more    more      big    med   good
1727    low   low  5more    more      big   high  vgood

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   str
 1   maint     1728 non-null   str
 2   doors     1728 non-null   str
 3   persons   1728 non-null   str
 4   lug_boot  1728 non-null   str
 5   safety    1728 non-null   str
 6   class     1728 non-null   str
dtypes: str(7)
memory usage: 133.5 KB

In [11]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
for col in col_names:
    print(df[col].value_counts())

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64
persons
2       576
4       576
more    576
Name: count, dtype: int64
lug_boot
small    576
med      576
big      576
Name: count, dtype: int64
safety
low     576
med     576
high    576
Name: count, dtype: int64
class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [12]:
df['class'].value_counts()

class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [14]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

### Declare feature vector and target variable

In [15]:
x = df.drop(['class'],axis=1) # 1 means column
y = df['class']

In [19]:
x.head()

  buying  maint doors persons lug_boot safety
0  vhigh  vhigh     2       2    small    low
1  vhigh  vhigh     2       2    small    med
2  vhigh  vhigh     2       2    small   high
3  vhigh  vhigh     2       2      med    low
4  vhigh  vhigh     2       2      med    med

In [18]:
y.value_counts()

class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

### Split data into separate training and test sets

In [20]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = 42)

In [21]:
x_train.head()

     buying  maint  doors persons lug_boot safety
48    vhigh  vhigh      3    more      med    low
468    high  vhigh      3       4    small    low
155   vhigh   high      3    more    small   high
1721    low    low  5more    more    small   high
1208    med    low      2    more    small   high

In [23]:
x_train.shape, x_test.shape

((1157, 6), (571, 6))

In [24]:
y_train.shape, y_test.shape

((1157,), (571,))

In [27]:
x_train.dtypes

buying      str
maint       str
doors       str
persons     str
lug_boot    str
safety      str
dtype: object

In [28]:
x_train.head()

     buying  maint  doors persons lug_boot safety
48    vhigh  vhigh      3    more      med    low
468    high  vhigh      3       4    small    low
155   vhigh   high      3    more    small   high
1721    low    low  5more    more    small   high
1208    med    low      2    more    small   high

In [30]:
import category_encoders as ce

In [31]:
# encode variables with ordinal encoding
encoder = ce.OrdinalEncoder(cols=['buying', 'maint', 'doors', 'persons',
                                  'lug_boot', 'safety'])

In [33]:
x_train = encoder.fit_transform(x_train)
x_test = encoder.transform(x_test)

x_train.head()

In [36]:
x_train.dtypes

buying      int64
maint       int64
doors       int64
persons     int64
lug_boot    int64
safety      int64
dtype: object

### Decision Tree Classifier with criterion gini index

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=0)

In [40]:
clf_gini.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=0)

### Predict the Test set results with criterion gini index

In [42]:
y_pred_gini = clf_gini.predict(x_test)

In [43]:
y_pred_gini[:10]

array(['unacc', 'good', 'unacc', 'acc', 'unacc', 'acc', 'unacc', 'unacc',
       'acc', 'unacc'], dtype=object)

In [44]:
from sklearn.metrics import accuracy_score
print('Model accuracy with  gini index: {0:0.4f}'. format(accuracy_score(y_test, y_pred_gini)))

Model accuracy with  gini index: 0.8441

### Compare the train-set and test-set accuracy

In [46]:
y_pred_train_gini = clf_gini.predict(x_train)
y_pred_train_gini

array(['unacc', 'unacc', 'unacc', ..., 'acc', 'unacc', 'good'],
      shape=(1157,), dtype=object)

In [47]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train_gini)))

Training-set accuracy score: 0.8539

### Check for overfitting and underfitting

In [49]:
print('Training set score: {:.4f}'.format(clf_gini.score(x_train, y_train)))

print('Test set score: {:.4f}'.format(clf_gini.score(x_test, y_test)))

Training set score: 0.8539
Test set score: 0.8441