In [1]:
import pandas as pd
import numpy as np

# Series

In [2]:
s = pd.Series([1,2,3,4], index=['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [3]:
enteries = {'swift':649000,
           'santro':391000,
           'audi':5476000,
           'elantra':1786000,
           'bolero':1091000}
car_series = pd.Series(data = enteries, name = "price")
car_series

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [4]:
# Cars with price more than 10 lakhs
car_series[car_series>1000000]

audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [5]:
car_series[car_series>1000000].index[0]

'audi'

In [6]:
car_series[car_series>1000000].values[1]

np.int64(1786000)

In [7]:
car_series[(car_series>1000000) & (car_series<2000000)]

elantra    1786000
bolero     1091000
Name: price, dtype: int64

#### loc[]

In [8]:
car_series.loc['swift']

np.int64(649000)

In [9]:
car_series.loc[['swift']]

swift    649000
Name: price, dtype: int64

In [10]:
car_series.loc[['swift','audi']]

swift     649000
audi     5476000
Name: price, dtype: int64

In [11]:
car_series.loc['swift':'audi']

swift      649000
santro     391000
audi      5476000
Name: price, dtype: int64

### iloc[]

In [12]:
car_series.iloc[0], car_series.iloc[[2]]

(np.int64(649000),
 audi    5476000
 Name: price, dtype: int64)

In [13]:
car_series.iloc[[0,2,4]]

swift      649000
audi      5476000
bolero    1091000
Name: price, dtype: int64

In [14]:
car_series.iloc[0:]

swift       649000
santro      391000
audi       5476000
elantra    1786000
bolero     1091000
Name: price, dtype: int64

In [15]:
car_series.iloc[::-1]

bolero     1091000
elantra    1786000
audi       5476000
santro      391000
swift       649000
Name: price, dtype: int64

# DataFrame

In [16]:
d =pd.DataFrame({
    'Product':['A','B','C'],
    'Price': [200,100,150],
    'Quantity': [5,4,7]
})
d

  Product  Price  Quantity
0       A    200         5
1       B    100         4
2       C    150         7

### Creating CSV file from dataframe

In [17]:
d.to_csv('product_info.csv',index=False)

### Reading CSV file

In [18]:
data = pd.read_csv('product_info.csv')
print(data)

  Product  Price  Quantity
0       A    200         5
1       B    100         4
2       C    150         7

In [19]:
data['Price']

0    200
1    100
2    150
Name: Price, dtype: int64

In [20]:
data[['Price','Product']]

   Price Product
0    200       A
1    100       B
2    150       C

In [21]:
data.head(2)

  Product  Price  Quantity
0       A    200         5
1       B    100         4

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Product   3 non-null      object
 1   Price     3 non-null      int64
 2   Quantity  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [23]:
data.describe()

       Price  Quantity
count    3.0  3.000000
mean   150.0  5.333333
std     50.0  1.527525
min    100.0  4.000000
25%    125.0  4.500000
50%    150.0  5.000000
75%    175.0  6.000000
max    200.0  7.000000

In [24]:
df =pd.read_csv("data_clean.csv")
df.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [25]:
df.isnull().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

### Imputataion with Mean,Median,Mode

In [26]:
df.Ozone

0      41.0
1      36.0
2      12.0
3      18.0
4       NaN
       ...
153    41.0
154    30.0
155     NaN
156    14.0
157    18.0
Name: Ozone, Length: 158, dtype: float64

In [27]:
ozone_median =df.Ozone.median()
ozone_median

30.5

In [28]:
df['Ozone'].fillna(ozone_median, inplace=True)
df.Ozone

0      41.0
1      36.0
2      12.0
3      18.0
4      30.5
       ...
153    41.0
154    30.0
155    30.5
156    14.0
157    18.0
Name: Ozone, Length: 158, dtype: float64

In [29]:
df["Solar.R"]

0      190.0
1      118.0
2      149.0
3      313.0
4        NaN
       ...
153    190.0
154    193.0
155    145.0
156    191.0
157    131.0
Name: Solar.R, Length: 158, dtype: float64

In [30]:
solar_mean = df["Solar.R"].mean()
solar_mean

np.float64(185.40397350993376)

In [31]:
df['Solar.R'].fillna(solar_mean, inplace=True)
df['Solar.R']

0      190.000000
1      118.000000
2      149.000000
3      313.000000
4      185.403974
          ...
153    190.000000
154    193.000000
155    145.000000
156    191.000000
157    131.000000
Name: Solar.R, Length: 158, dtype: float64

In [32]:
df.Weather

0       S
1       C
2      PS
3       S
4       S
       ..
153     C
154    PS
155     S
156     S
157     C
Name: Weather, Length: 158, dtype: object

In [33]:
Weather_mode = df.Weather.mode()[0]
Weather_mode

'S'

In [34]:
df.Weather.fillna(Weather_mode,inplace=True)
df.Weather

0       S
1       C
2      PS
3       S
4       S
       ..
153     C
154    PS
155     S
156     S
157     C
Name: Weather, Length: 158, dtype: object

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  158 non-null    int64
 1   Ozone       158 non-null    float64
 2   Solar.R     158 non-null    float64
 3   Wind        158 non-null    float64
 4   Temp C      158 non-null    object
 5   Month       158 non-null    object
 6   Day         158 non-null    int64
 7   Year        158 non-null    int64
 8   Temp        158 non-null    int64
 9   Weather     158 non-null    object
dtypes: float64(3), int64(4), object(3)
memory usage: 12.5+ KB

### Aggregation - (groupby, mean)

In [39]:
weather_group = df.groupby('Weather')
print(weather_group['Temp'].mean())

Weather
C     77.734694
PS    76.872340
S     78.370968
Name: Temp, dtype: float64

In [40]:
month_group = df.groupby('Month')
print(month_group['Wind'].max())

Month
5      20.1
6      20.7
7      14.9
8      15.5
9      16.6
May    12.0
Name: Wind, dtype: float64